name: package updater

on:
    workflow_dispatch:
        inputs:
            repository_name:
                description: 'Repository name'
                required: true
                type: string
            version:
                description: 'Version'
                required: true
                type: string
    workflow_call:
        inputs:
            repository_name:
                description: 'Repository name'
                required: true
                type: string
            version:
                description: 'Version'
                required: true
                type: string
        secrets:
            access-token:
                required: true


jobs:
    update:
        runs-on: ubuntu-latest

        env:
            REPOSITORY_NAME: ${{ github.event.inputs.repository_name | inputs.repository_name }}
            VERSION: ${{ github.event.inputs.version | inputs.version }}
        
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                repository: niwaniwa/vpm.niri.la
                token: ${{ secrets.access-token || github.token }}
              
            - uses: snow-actions/git-config-user@v1.0.0

            - uses: denoland/setup-deno@v1
              with:
                deno-version: v1.x

            - name: Run update script
              run: deno run --allow-env --allow-net --allow-read --allow-write --allow-run update-scripts/update-package.ts
              timeout-minutes: 10
              env:
                VPM_JSON_PATH: "vpm.json"
